# Generated by Django 3.2.14 on 2022-07-29 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAlerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedalerts',
            name='target_achieved_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
