# Generated by Django 3.2.14 on 2022-07-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAlerts', '0002_deletedalerts_target_achieved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='status',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deletedalerts',
            name='status',
            field=models.TextField(max_length=20),
        ),
    ]
