# Generated by Django 3.2.14 on 2022-07-29 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PriceAlerts', '0003_auto_20220729_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeletedAlerts',
            new_name='AllBackupAlerts',
        ),
    ]
