# Generated by Django 3.2.14 on 2022-07-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAlerts', '0004_rename_deletedalerts_allbackupalerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbackupalerts',
            name='target_achieved_date',
        ),
        migrations.AlterField(
            model_name='allbackupalerts',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
