# Generated by Django 3.2.14 on 2022-07-29 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAlerts', '0005_auto_20220729_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbackupalerts',
            name='alert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PriceAlerts.alerts'),
            preserve_default=False,
        ),
    ]
